### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by richie-omondi**
Contribution to issue #2 that adds the Embedded Rust repo to the organization profile

### CODE REVIEW

**Comment by 448-OG** [comment]
Looks good

**Review by 448-OG — APPROVED** [review]
Thanks for contributing to this repository. The solution is as intended

**Review by kiarie404 — APPROVED** [review]

**Comment by 448-OG** [comment]
@richie-omondi  can you sign your commits. Merging your commit to master branch requires all commits to be signed by their author

**Comment by richie-omondi** [comment]
> @richie-omondi can you sign your commits. Merging your commit to master branch requires all commits to be signed by their author

Okay. Will do.

**Review by nyakiomaina — APPROVED** [review]

**Review by 448-OG — APPROVED** [review]

**Comment by 448-OG** [comment]
LGTM. Thanks for signing the commits.

**Pull request merged**
